//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APTA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EVENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EVENT()
        {
            this.STUDENTS = new HashSet<STUDENT>();
        }
    
        public int EVENT_ID { get; set; }
        [Required]
        [Display(Name = "Event Name")]
        public string NAME { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd MMM yyyy}")]
        [Display(Name = "Date")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DATE { get; set; }
        public int ORGANISER_ID { get; set; }
        public int LocationID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual CENTER CENTER { get; set; }
        public virtual ORGANISER ORGANISER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENT> STUDENTS { get; set; }
    }
}
